### ISSUE TITLE
I want to get rid of that placeholder. Any tips for adding users?

### ISSUE THREAD

**Issue by PiiickleRiiick** [QuentinGibson/College-Planner#5]

**Comment by PiiickleRiiick** [comment]
@QuentinGibson I need help with this got anything?

**Comment by QuentinGibson** [comment]
Don't about it Mr.Smith I'm going to make a commit right now.
![image](https://user-images.githubusercontent.com/16958080/86193819-e98b8480-bb1a-11ea-8d65-66083e026a1f.png)
